MiniSwitch/Models/Route.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MiniSwitch.Models
{
    public class Route
    {
        public Guid Id { get; set; }

        [Required]
        public string Name { get; set; }
        [Required]
        public SinkNode SinkNode { get; set; }

        public string CardPAN { get; set; }
        public string Description { get; set; }
    }
}

MiniSwitch/ViewModels/RouteViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using MiniSwitch.Models;

namespace MiniSwitch.ViewModels
{
    public class RouteViewModel
    {
        public Guid Id { get; set; }

        [Required]
        public string Name { get; set; }
        [Required]
        public Guid SinkNodeID { get; set; }

        public SinkNode SinkNode { get; set; }

        public string BIN { get; set; }
        public string Description { get; set; }
    }
}

MiniSwitch/Controllers/RouteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MiniSwitch.Models;
using MiniSwitch.Services.RouteServices;
using MiniSwitch.Services.SinkNodeServices;
using MiniSwitch.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MiniSwitch.Controllers
{
    public class RouteController : Controller
    {
        private IRouteService _routeService;
        private ISinkNodeService _sinkNodeService;

        public RouteController(IRouteService routeService, ISinkNodeService sinkNodeService)
        {
            _routeService = routeService;
            _sinkNodeService = sinkNodeService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string searchString = "", int? pageNumber = 1)
        {
            ViewData["CurrentFilter"] = searchString;
            var routes = await _routeService.FetchAll(searchString, pageNumber);
            var sinkNodes = await _sinkNodeService.FetchAll();
            ViewBag.SinkNodes = sinkNodes.Where(x => x.Status == Enums.NodeStatusEnum.Active).ToList();
            return View(routes);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromForm] RouteViewModel model)
        {
            var response = await _routeService.Edit(model);
            if (response.isSuccess)
                TempData["Success"] = response.Message;
            else
                TempData["Error"] = response.Message;
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Create([FromForm] RouteViewModel model)
        {
            var response = await _routeService.Create(model);
            if (response.isSuccess)
                TempData["Success"] = response.Message;
            else
                TempData["Error"] = response.Message;
            return RedirectToAction("Index");
        }
    }
}

MiniSwitch/Views/Route/Index.cshtml
@model PaginatedList<Route>
@{
    ViewData["Title"] = "Route Management";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
    List<SinkNode> SinkNodes = ViewBag.SinkNodes;
}
<link rel="stylesheet" href="~/css/user.css" />

<div class="container">
    <p class="text-center text-success">@TempData["Success"]</p>
    <p class="text-center text-danger">@TempData["Error"]</p>

    <button class="mt-3 btn-sm col-md-3" type="button" data-toggle="modal" data-target="#modal">Add New Route</button>
    <form asp-action="Index" method="get">
        <div class="form-actions no-color col-md-12 mt-5">
            <div class="row">
                <p>Search:</p>
                <input type="text" class="form-control col-md-3 m-1" name="SearchString" value="@ViewData["CurrentFilter"]" />
                <button type="submit" class="btn-sm col-md-2 m-1">Search</button>
                <hr />
                <a asp-action="Index" class="m-1">Back to Full List</a>
            </div>
        </div>
    </form>
    <table id="meetingTable" class="table table-striped table-hover table-sm table-bordered">
        <thead class="">
            <tr>
                <th class="col-md-2">Id</th>
                <th class="col-md-4">Name</th>
                <th class="col-md-3">Description</th>
                <th class="col-md-3">Sink Node</th>
                <th class="col-md-3">Card BIN</th>
            </tr>
        </thead>
        <tbody>
            @{
                if (Model != null)
                {
                    if (Model.Count > 0)
                    {
                        foreach (var route in Model)
                        {
                        <tr>
                            <td class="col-md-2">@string.Join("", route.Id.ToString().Take(10))...</td>
                            <td class="col-md-4">@route.Name</td>
                            <td class="col-md-3">@route.Description</td>
                            <td class="col-md-3">@route.SinkNode.Name</td>
                            <td class="col-md-3">@route.BIN</td>
                            <td class="col-md-2"><button class="btn-sm" id="@route.Id.ToString()" type="button" data-toggle="modal" data-target="#editModal" onclick="GetEditNode(event)">Edit</button></td>
                        </tr>
                        }

                        <div class="">
                            @if (Model.HasPreviousPage)
                            {
                                <button class="text-left mr-5 btn-sm" asp-action="Index" asp-route-pageNumber="@(Model.PageIndex - 1)">Previous</button>
                            }
                            @if (Model.HasNextPage)
                            {
                                <button class="text-right ml-5 btn-sm" asp-action="Index" asp-route-pageNumber="@(Model.PageIndex + 1)">Next</button>
                            }
                        </div>
                    }
                    else
                    {
                        <p class="text-center">No Routes added yet. Add a Route</p>
                    }
                }
            }
        </tbody>
    </table>


    <div id="modal" class="modal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body m-3">
                    <h3 class="text-center mb-3">Route</h3>
                    <form method="post" asp-action="Create" asp-controller="Route">
                        <div class="row">
                            <input class="form-control m-2 col-md-5" name="Name" type="text" placeholder="Name" required />
                            <div class="">
                                <select name="SinkNodeID" class="form-control m-2" required>
                                    <option value="">Select Sink Node</option>
                                    @foreach (SinkNode node in SinkNodes)
                                    {
                                        <option class="m-1" value="@node.Id">@node.Name</option>
                                    }
                                </select>
                            </div>
                            <input class="form-control m-2 col-md-5" name="BIN" type="text" placeholder="BIN" maxlength="6" required />
                            <textarea class="form-control m-2 col-md-10" name="Description" type="text" placeholder="Description" required></textarea>
                        </div>
                        <button class="mt-3 btn-sm" type="submit">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>



    <div id="editModal" class="modal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body m-3">
                    <h3 class="text-center mb-3">Route</h3>
                    <form method="post" asp-action="Edit" asp-controller="Route">
                        <div class="row">
                            <input class="form-control m-2 col-md-5" id="editId" name="Id" type="text" placeholder="Id" required hidden />
                            <input class="form-control m-2 col-md-5" name="Name" type="text" placeholder="Name" required />
                            <div class="">
                                <select name="SinkNodeID" class="form-control m-2" required>
                                    <option value="">Select Sink Node</option>
                                    @foreach (SinkNode node in SinkNodes)
                                    {
                                        <option class="m-1" value="@node.Id">@node.Name</option>
                                    }
                                </select>
                            </div>
                            <input class="form-control m-2 col-md-5" name="BIN" type="text" placeholder="BIN" maxlength="6" required />
                            <textarea class="form-control m-2 col-md-10" name="Description" type="text" placeholder="Description" required></textarea>
                            
                        </div>
                        <button class="mt-3 btn-sm" type="submit">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>function GetEditNode(event) {
        var target = event.target || event.srcElement;

        document.getElementById("editId").value = target.id;
    }</script>