MiniSwitch/Models/SourceNode.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Net;
using MiniSwitch.Enums;

namespace MiniSwitch.Models
{
    public class SourceNode
    {
        public Guid Id { get; set; }

        [Required]
        public string Name { get; set; }
        [Required]
        public string HostName { get; set; }
        [Required]
        public string IpAddress { get; set; }
        [Required]
        public string Port { get; set; }
        [Required]
        public Scheme Scheme { get; set; }

        public NodeStatusEnum Status { get; set; }
    }
}

MiniSwitch/ViewModels/SourceNodeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using MiniSwitch.Enums;
using MiniSwitch.Models;

namespace MiniSwitch.ViewModels
{
    public class SourceNodeViewModel
    {
        public Guid Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string HostName { get; set; }
        [Required]
        public string IpAddress { get; set; }
        [Required]
        public string Port { get; set; }
        [Required]
        public Guid SchemeID { get; set; }
        public Scheme Scheme { get; set; }

        public NodeStatusEnum Status { get; set; }
    }
}

MiniSwitch/Controllers/SourceNodeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MiniSwitch.Helpers;
using MiniSwitch.Models;
using MiniSwitch.Services.SchemeServices;
using MiniSwitch.Services.SourceNodeServices;
using MiniSwitch.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MiniSwitch.Controllers
{
    public class SourceNodeController : Controller
    {
        private ISourceNodeService _sourceNodeService;
        private ISchemeService _schemeService;

        public SourceNodeController(ISourceNodeService sourceNodeService, ISchemeService schemeService)
        {
            _sourceNodeService = sourceNodeService;
            _schemeService = schemeService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string searchString = "", int? pageNumber = 1)
        {
            ViewData["CurrentFilter"] = searchString;
            var sourceNodes = await _sourceNodeService.FetchAll(searchString, pageNumber);
            ViewBag.Schemes = await _schemeService.FetchAll();

            return View(sourceNodes);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromForm] SourceNodeViewModel sourceNode)
        {
            var response = await _sourceNodeService.Edit(sourceNode);
            if (response.isSuccess)
                TempData["Success"] = response.Message;
            else
                TempData["Error"] = response.Message;
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Create([FromForm] SourceNodeViewModel sourceNode)
        {
            var response = await _sourceNodeService.Create(sourceNode);
            if (response.isSuccess)
                TempData["Success"] = response.Message;
            else
                TempData["Error"] = response.Message;
            return RedirectToAction("Index");
        }
    }
}

MiniSwitch/Views/SourceNode/Index.cshtml
@model PaginatedList<SourceNode>
@{
    ViewData["Title"] = "Source Node Management";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
    List<Scheme> schemes = ViewBag.Schemes;
}
<link rel="stylesheet" href="~/css/user.css" />

<div class="container">
    <p class="text-center text-success">@TempData["Success"]</p>
    <p class="text-center text-danger">@TempData["Error"]</p>

    <button class="mt-3 btn-sm col-md-3" type="button" data-toggle="modal" data-target="#modal">Add New Source Node</button>
    <form asp-action="Index" method="get">
        <div class="form-actions no-color col-md-12 mt-5">
            <div class="row">
                <p>Search:</p>
                <input type="text" class="form-control col-md-3 m-1" name="SearchString" value="@ViewData["CurrentFilter"]" />
                <button type="submit" class="btn-sm col-md-2 m-1">Search</button>
                <hr />
                <a asp-action="Index" class="m-1">Back to Full List</a>
            </div>
        </div>
    </form>
    <table id="meetingTable" class="table table-striped table-hover table-sm table-bordered">
        <thead class="">
            <tr>
                <th class="col-md-4">Name</th>
                <th class="col-md-3">Host Name</th>
                <th class="col-md-3">IP Address</th>
                <th class="col-md-2">Port</th>
                <th class="col-md-2">Status</th>
                <th class="col-md-2">Scheme</th>
            </tr>
        </thead>
        <tbody>
            @{
                if (Model != null)
                {
                    if (Model.Count > 0)
                    {
                        foreach (var node in Model)
                        {
                        <tr>
                            <td class="col-md-4">@node.Name</td>
                            <td class="col-md-3">@node.HostName</td>
                            <td class="col-md-3">@node.IpAddress</td>
                            <td class="col-md-2">@node.Port</td>
                            <td class="col-md-2">@node.Status.ToString()</td>
                            <td class="col-md-2">@node.Scheme.Name</td>
                            <td class="col-md-2"><button class="btn-sm" id="@node.Id.ToString()" type="button" data-toggle="modal" data-target="#editModal" onclick="GetEditNode(event)">Edit</button></td>
                        </tr>
                        }

                        <div class="">
                            @if (Model.HasPreviousPage)
                            {
                                <button class="text-left mr-5 btn-sm" asp-action="Index" asp-route-pageNumber="@(Model.PageIndex - 1)">Previous</button>
                            }
                            @if (Model.HasNextPage)
                            {
                                <button class="text-right ml-5 btn-sm" asp-action="Index" asp-route-pageNumber="@(Model.PageIndex + 1)">Next</button>
                            }
                        </div>
                    }
                    else
                    {
                        <p class="text-center">No Source Node added. Add a Source Node</p>
                    }
                }
            }
        </tbody>
    </table>


    <div id="modal" class="modal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body m-3">
                    <h3 class="text-center mb-3">Source Node</h3>
                    <form method="post" asp-action="Create" asp-controller="SourceNode">
                        <div class="row">
                            <input class="form-control m-2 col-md-5" name="Name" type="text" placeholder="Name" required />
                            <input class="form-control m-2 col-md-5" name="HostName" type="text" placeholder="Host Name" required />
                            <input class="form-control m-2 col-md-5" name="IpAddress" type="text" placeholder="IP Address" required />

                            <input class="form-control m-2 col-md-5" name="Port" type="text" placeholder="Port" required />
                            <div class="m-1">
                                <select name="Status" class="form-control m-2" required>
                                    <option value="">Select Node Status</option>
                                    @foreach (var status in System.Enum.GetValues(typeof(MiniSwitch.Enums.NodeStatusEnum)))
                                    {
                                        <option class="m-1" value="@status" asp-for="Status">@status</option>
                                    }
                                </select>
                            </div>
                            <div class="m-1">
                                <select name="SchemeID" class="form-control m-2" required>
                                    <option value="">Select Scheme</option>
                                    @foreach (var scheme in schemes)
                                    {
                                        <option class="m-1" value="@scheme.Id">@scheme.Name</option>
                                    }
                                </select>
                            </div>
                        </div>
                        <button class="mt-3 btn-sm" type="submit">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>



    <div id="editModal" class="modal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body m-3">
                    <h3 class="text-center mb-3">Source Node</h3>
                    <form method="post" asp-action="Edit" asp-controller="SourceNode">
                        <div class="row">
                            <input class="form-control m-2 col-md-5" id="editId" name="Id" type="text" placeholder="Name" required hidden />

                            <input class="form-control m-2 col-md-5" name="Name" type="text" placeholder="Name" required />
                            <input class="form-control m-2 col-md-5" name="HostName" type="text" placeholder="Host Name" required />
                            <input class="form-control m-2 col-md-5" name="IpAddress" type="text" placeholder="IP Address" required />

                            <input class="form-control m-2 col-md-5" name="Port" type="text" placeholder="Port" required />
                            <div class="m-1">
                                <select name="Status" class="form-control m-2" required>
                                    <option value="">Select Node Status</option>
                                    @foreach (var status in System.Enum.GetValues(typeof(MiniSwitch.Enums.NodeStatusEnum)))
                                    {
                                        <option class="m-1" value="@status" asp-for="Status">@status</option>
                                    }
                                </select>
                            </div>
                            <div class="m-1">
                                <select name="SchemeID" class="form-control m-2" required>
                                    <option value="">Select Scheme</option>
                                    @foreach (var scheme in schemes)
                                    {
                                        <option class="m-1" value="@scheme.Id">@scheme.Name</option>
                                    }
                                </select>
                            </div>
                        </div>
                        <button class="mt-3 btn-sm" type="submit">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>function GetEditNode(event) {
        var target = event.target || event.srcElement;

        document.getElementById("editId").value = target.id;
    }</script>